Rationalization
olegkarman/Team1_CarRental pull request #23
Opened 2024-06-08 11:33 UTC by frostysh

To rationalize internal logic of Car sub-infrastructure.

2024-06-08 17:32 UTC, frostysh commented
Approvchiky plz...

2024-06-09 07:11 UTC, olegkarman commented
перестань добабляти ці коментарі та ще й міняти їх в кожному ПР. коли ти будеш робити справжній проект і в тебе там буде відбуватись подібне, тобі такі ПР-и ніхто не апрувне. просто подивляться що там зміни в 50+ файлах і одразу відправлять на доопрацювання

2024-06-09 07:12 UTC, olegkarman requested changes
почитай коментар вище

2024-06-09 07:19 UTC, frostysh commented
> перестань добавляти ці коментарі та ще й міняти їх в кожному ПР. коли ти будеш робити справжній проект і в тебе там буде відбуватись подібне, тобі такі ПР-и ніхто не апрувне. просто подивляться що там зміни в 50+ файлах і одразу відправлять на доопрацювання
> 
> коментар, якщо він існує в коді, він коротний, лаконічний і пояснює якусь, можливо не одразу очевидну логіку. а лишати коментарі просто для того щоб лишити коментарі, це не ок.
> 
> якщо метод названий правильно, його не потрібно пояснювати, бо його назва пояснить для чого він. проперті не треба пояснювати, бо їхнє призначення так само випливає з назви.

Гм... Спробую видалити.

2024-06-09 07:30 UTC, frostysh commented
> почитай коментар вище

Було видалено більшість коментарів. А також змінено назву одного методу в менеджер-класі.

2024-06-10 08:05 UTC, frostysh commented
Naming in Customer.cs fixed. I did not touch any of namespaces though...

2024-06-10 08:55 UTC, olegkarman approved these changes

2024-06-10 12:26 UTC, merged